### ISSUE TITLE
NPC dialog source

### ISSUE THREAD

**Issue by exectails** [NoCode-NoLife/melia#103]
Our NPC's dialog code currently looks something like this:
```lua
if select("TUTO_GIRL_basic_02", "!@#$TUTO_GIRL_select01#@!", "!@#$Auto_JongLyo#@!") ~= 1 then
	return
end
if select("TUTO_GIRL_basic_03", "!@#$TUTO_GIRL_select02#@!", "!@#$Auto_JongLyo#@!") ~= 1 then
	return
end
if select("TUTO_GIRL_basic_04", "!@#$TUTO_GIRL_select03#@!", "!@#$Auto_JongLyo#@!") ~= 1 then
	return
end

msg("TUTO_GIRL_basic_05")
```
We take advantage of the fact that the client has the dialogues for all NPCs, and just send localization keys. This has the advantage that it's pretty easy to create NPCs from logs, and we don't have to worry about localization, as long as there is an official translation for your language.

However, we also put ourselves at the mercy of the client. Any string can change at any time, just like their keys, and the script we wrote might not make any sense anymore after a few updates. That wouldn't be a problem if we sent the actual text, without relying on the client. It would also allow users to actually figure out what's going on in a script, instead of just guessing, based on structure and keys.

```lua
if select("It would not be strange if the world ended tomorrow.{nl}However, I just want to know. Why the goddesses disappeared..", "Ask about the disappearance of the goddesses", "Cancel") ~= 1 then
	return
end
if select("I'm not sure I understand it completely, but what I'm sure of is that the goddesses didn't disappear all at once.", "Ask what happened", "Cancel") ~= 1 then
	return
end
if select("Goddess Vakarine left us shortly before Medzio Diena.{nl}Both Zemyna and Ausrine disappeared soon after.{nl}It's already been four years since.", "I think you forgot to mention Goddess Laima", "Cancel") ~= 1 then
	return
end

msg("She has never appeared before.{nl}Although I've read somewhere that she does appear every now and then...")
```
Typing all this out is certainly more work though, even if a Pale plugin could help with that, and I don't know if anyone will actually care about the dialog. It should be said though that writing the script would also be easier with actual text.

I thought I'd create a discussion for it, because I'm not sure which is better, and we should definitely stick to one.

**Comment by celophi** [comment]
I can see why this feature would be desired; however, I'm not knowledgeable enough about how localization would work without the keys here. @exectails Would you mind explaining this in depth?

Technically, the only issue that I could see using this method is that the packet size would increase due to sending long character strings. We would do well to make sure that they are zipped before being sent.  And of course, whatever process that we use to convert keys into strings needs to be robust and maintained (which involves tools not part of Melia).

**Comment by exectails** [comment]
>Would you mind explaining this in depth?

Sure. There are various ways you can tackle localization, but my personal favorite is gettext. Here you use keys as well, but instead of something like "SOME_TEXT", which is then turned into "This is some text.", you actually write it out, and that becomes the default for when no translation is available.

All strings that are to be localized need to be wrapped in a function call, for example `L("This is some text.")`, with the function looking up the key, and either returning an available translation, or just the key again, as the default.

To create a localization database for a project you use a specialized parser that basically runs over all the source code, and searches for these function calls, creating a file out of them that you can then, for example, give to translators.

The special thing about gettext is that it supports plurals properly. And not only the 1 plural form we know from English, but even the 6 or so forms of plurals that exist in other languages, so something like "You have X items." can be translated in a proper way.

```csharp
var text = string.Format(LN("You have {0} item.", "You have {0} items.", itemCount), itemCount);
```
Gettext will choose the correct plural form based on the amount and return the string, which is then used in the format to get the final result.

The one disadvantage to this system is the function wrapper around all strings.

```lua
if select(L("It would not be strange if the world ended tomorrow.{nl}However, I just want to know. Why the goddesses disappeared.."), L("Ask about the disappearance of the goddesses"), L("Cancel")) ~= 1 then
	return
end
if select(L("I'm not sure I understand it completely, but what I'm sure of is that the goddesses didn't disappear all at once."), L("Ask what happened"), L("Cancel")) ~= 1 then
	return
end
if select(L("Goddess Vakarine left us shortly before Medzio Diena.{nl}Both Zemyna and Ausrine disappeared soon after.{nl}It's already been four years since."), L("I think you forgot to mention Goddess Laima"), L("Cancel")) ~= 1 then
	return
end

msg(L("She has never appeared before.{nl}Although I've read somewhere that she does appear every now and then..."))
```

>the only issue that I could see using this method is that the packet size

It does increase the packet size, but I think it's fine. Players don't spend so much time in dialogues that it would create a bottle neck. And many games don't send keys, but the full dialog. Though we could certainly compress it, provided that the dialog functions support it. I don't see any compression setup though.
