### ISSUE TITLE
Is this project alive ? 

### ISSUE THREAD

**Issue by karocksjoelee** [NoCode-NoLife/melia#144]
I 've seen the last commit is 1 day ago , so I suppose it is back on ? 
I don't know C# or .NET , know a little bit MySQL , I am a JS developer , using node / mongodb / anglar .
Any chance I can be apart of this project ? I can set-up a web-base GM app or sth. like that . 

Really looking forward about this game going private server : P

**Comment by exectails** [comment]
Well... let's say it's on life support. I started keeping it up-to-date again a few weeks ago when there were a few people interested in working on it, but most of those people have been silent again for weeks now, and no major additions have been made either yet iirc.

Any help is welcome though, feel free to look into our web server and see what you can do with it. Also see our [contributions guidelines](https://github.com/aura-project/melia/blob/master/CONTRIBUTING.md) regarding making pull requests.

**Comment by karocksjoelee** [comment]
So .. the main problem of this project is lack of man-power ? what kind of developer you are looking for ?

**Comment by exectails** [comment]
Someone else who can write a server emulator would be great.

**Comment by lRaikeNl** [comment]
I'm currently busy with work, But I will continue helping you guys when I have vacation. I do have a full time job, though.

**Comment by exectails** [comment]
That's the thing with server emulator development, the people that are into it are usually either younger beginners with a lot of time on their hands, but who don't have enough experience to really help "yet", or older, more experienced coders, who don't have enough time or motivation to work seriously on such a side-project.

In my experience it's very rare to find programmers who have the experience to write a server emulator from scratch *and* enough time and motivation to actually dedicate months and years of their life to it.

**Comment by keitenai** [comment]
Glad to see this project moving again.
One issue that i have come across with this is that there is no available standalone client for this.

**Comment by keitenai** [comment]
Glad to see this project moving again.
One issue that i have come across with this is that there is no released standalone client for this.

**Comment by exectails** [comment]
>there is no available standalone client for this.

You mean one without Steam?

**Comment by keitenai** [comment]
yeah, without steam

**Comment by exectails** [comment]
I guess that's not ideal, but you can always copy the latest client onto a USB drive or something and take it with you. I don't think you need Steam to connect to Melia.

**Comment by Hirasu** [comment]
If you just want connect to melia, use this: "Client_tos.exe -SERVICE"
