### ISSUE TITLE
Answer me a question

### ISSUE THREAD

**Issue by gigantescu** [NoCode-NoLife/melia#149]
I was testing everything until I melia: channel, showed me this, could you explain, what would this be?
01/03/2018 21:15:37 [Warning] - CZ_RUN_GAMEEXIT_TIMER: User 'aa' tried to transfer to 'BLANK' which is an unknown state.
01/03/2018 21:19:35 [Debug] - PacketHandler: No handler found for '0C6C', CZ_SKILL_TARGET_ANI.

--------------

Has this project died?

**Comment by exectails** [comment]
Can you tell us more about the circumstances during which you got this warning? What were you doing, what happened around you?

The warning means that the server got an unexpected request from the client, with a value it didn't know how to handle. This is either a bug/glitch or a value we didn't know about yet and hence aren't handling. The debug message means that you tried to do something we haven't implemented yet. The server received the packet "CZ_SKILL_TARGET_ANI" from your client, but there is no handler for it yet, which means you can't use that function, presumably using a skill, yet.

>Has this project died?

I wouldn't call Melia dead, it's more like in a coma. Right now nobody capable of developing it further has the time or is interested enough to do so, but I'm still keeping it up to date with the latest client in case anyone wants to work on it.

**Comment by gigantescu** [comment]
This is when I use appraiser skill 1
------------------------------------------------------------------------------
03/03/2018 17:25:31 [Debug] - PacketHandler: No handler found for '0DEA', CZ_REGISTER_AUTOSELLER.
------------------------------------------------------------------------------
Op: 0DEA CZ_REGISTER_AUTOSELLER, Size: 360
------------------------------------------------------------------------------
0000   EA 0D 35 01 00 00 CE 30  00 00 68 01 61 61 61 61   ..5....0..h.aaaa
0010   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0020   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0030   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0040   00 00 00 00 00 00 00 00  00 00 00 00 01 00 00 00   ................
0050   60 02 1B 00 0D 7B 00 00  0D 7B 00 00 00 00 00 00   `...............
0060   01 00 00 00 0F 00 00 00  58 50 56 49 45 57 45 52   ........XPVIEWER
0070   5F 43 41 4C 43 55 4C 41  54 45 5F 54 49 43 4B 5D   _CALCULATE_TICK]
0080   20 65 74 63 49 6E 66 6F  5B 5B 73 74 72 69 6E 67    etcInfo[[string
0090   20 22 2D 2D 5B 5B 53 54  41 52 54 20 45 58 50 45    "--[[START EXPE
00A0   52 49 45 4E 43 45 20 44  41 54 41 5D 5D 2E 2E 2E   RIENCE DATA]]...
00B0   22 5D 3A 35 30 37 3A 20  61 74 74 65 6D 70 74 20   "]:507: attempt 
00C0   74 6F 20 63 6F 6E 63 61  74 65 6E 61 74 65 20 66   to concatenate f
00D0   69 65 6C 64 20 27 74 69  6D 65 54 69 6C 4C 65 76   ield 'timeTilLev
00E0   65 6C 27 20 28 61 20 6E  69 6C 20 76 61 6C 75 65   el' (a nil value
00F0   29 5D 20 6D 73 67 5B 5B  73 74 72 69 6E 67 20 22   )] msg[[string "
0100   2D 2D 5B 5B 53 54 41 52  54 20 45 58 50 45 52 49   --[[START EXPERI
0110   45 4E 43 45 20 44 41 54  41 5D 5D 2E 2E 2E 22 5D   ENCE DATA]]..."]
0120   3A 35 30 37 3A 20 61 74  74 65 6D 70 74 20 74 6F   :507: attempt to
0130   20 63 6F 6E 63 61 74 65  6E 61 74 65 20 66 69 65    concatenate fie
0140   6C 64 20 27 74 69 6D 65  54 69 6C 4C 65 76 65 6C   ld 'timeTilLevel
0150   27 20 28 61 20 6E 69 6C  20 76 61 6C 75 65 29 5D   ' (a nil value)]
0160   00 00 7D 00 7B 00 2F 00                            ....../.

**Comment by gigantescu** [comment]
CZ_SKILL_TARGET_ANI this always happens, in any typical situation, like talking to npcs, using spells, using weapons
------------

I want to work with him

**Comment by exectails** [comment]
I can't imagine that you got the "CZ_RUN_GAMEEXIT_TIMER" warning while you were talking to NPCs, and I told you why you get the unimplemented messages, stuff like skills doesn't work yet.

**Comment by gigantescu** [comment]
in npcs is different, in all appears, i do not have anything to say yet

when I enter the server
03/03/2018 23:00:50 [Warning] - CZ_RUN_GAMEEXIT_TIMER: User 'aa' tried to transfer to 'BLANK' which is an unknown state.


the ataccks and the spawn / respawn do not work?

**Comment by exectails** [comment]
You should assume that nothing works, because Melia isn't advanced enough yet to actually play the game.

**Comment by gigantescu** [comment]
these things like, the talk of npcs, skills, skills and among other, are all made in script? specifically in melia \ system \ scripts
if not, I wanted to know if it would be possible to have a more detailed explanation of this

**Comment by exectails** [comment]
NPCs are scripted, skills aren't. There is no skill system in place yet, so you basically can't add skills yet, unless you code the underlying system as well.
