### ISSUE TITLE
Monster spawning

### ISSUE THREAD

**Issue by Danil0v3s** [NoCode-NoLife/melia#152]
I'm currently looking for spawing monsters automatically functionality. Currently I'm stuck in the project way of doing things. So far I've found that if I just spawn random monsters on map by command, they often occur to be spawned somewhere users wouldn't be able to attack.
I would love hints and opinions, ~~I'll take a look into the aura project and see if I can find something useful~~

**Comment by daniloleemes** [comment]
> Like if you're standing close to a wall and the monster spawns inside it?
Yes, exactly that. I've found a fork of melia which the guy has implemented monsters, spawnzone and AI. I'll try to bring that to this fork

**Comment by exectails** [comment]
Closing this, as the basic functionality of creating spawners has been merged.
