### ISSUE TITLE
Stuck on character creation

### ISSUE THREAD

**Issue by Sighmir** [NoCode-NoLife/melia#156]
I think this packet must have changed or something, I don't really know much about these packets, I tried changing the size on the table to every number between 1040 and 1033 including them, but that would give me another message saying there was no handler for that packet. I am not sure if the second message is an error.

My problem is that after that packet is ignored, I get stuck on the character creation with no UI to create a character. I am not sure if that packet being ignored is related to me being stuck in the character creation area.

Heres an output of my LoginServer, all the others didn't show any unusual messages.
https://gist.github.com/Sighmir/a1fee0e5b8eb4d3a8ea0e69b5184121c

I hope this is useful in some way.

**Comment by Sighmir** [comment]
I figured out those things might be unrelated. I don't know if I am the only one getting stuck on character creation, but I think I might be, if everything is working fine for you this issue can be closed.

**Comment by exectails** [comment]
There were some packet and OP changes a few weeks ago, but I haven't gotten around to updating Melia yet. I'll try to look into it later today.

**Comment by Sighmir** [comment]
Thank you very much man! I really appreciate it. I am looking forward to supporting this project in any way I can, I know a little bit about programming and all your projects really interest me, I know I can learn a lot from your work.

**Comment by exectails** [comment]
I've updated the data, ops, and obviously outdated packets to i218535. I've only tested basics, like swapping equip and talking to NPCs, but it *seems* to be working again now. I'll close this for now, as the issue has been solved.

**Comment by Sighmir** [comment]
Thank you very much, the problem seems to be gone, I hope I can learn how to fix that in the future.
