### ISSUE TITLE
LoginServer no longer works with 2020 client

### ISSUE THREAD

**Issue by y4my4my4m** [NoCode-NoLife/melia#163]
`[Warning] - Invalid padding for '0003' (4480, 4457), from '127.0.0.1:65319'. Ignoring packet.`

Error message on either login or creating a new user.

**Comment by y4my4my4m** [comment]
So..changing `_sizes[CB_LOGIN]` to `4480` in `Op.cs` made that error go away.

However I still had issues login in (it would just close the connection right away)

I got to create a new user by hardcoding a username, I get the `User 'test' logged in.` now but it remain on the login page...

**Comment by exectails** [comment]
Thanks for your report. Melia hasn't been updated in a long while, so you're not gonna be able to connect with any recent clients. It's also difficult to get your hands on older clients, making Melia kind of useless in its current state. I want to update it again at some point, but haven't gotten around to it yet.
