### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by SalmanTKhan** [NoCode-NoLife/melia#197]
Currently, @exectails has implemented the Item's script function (which makes it accessible for items to call an associated Lua function based on what function was set on the itemdbs.txt), the scripts themselves have not been implemented, because most of the items require an underlying component, for example, some items provide a buff but without the buff handler, the item won't do much or some generate items from string provided.

**Comment by exectails** [comment]
Could you elaborate what this issue is about? If it's about implementing all scripts and their underlying systems the scope appears a bit large for one issue.

**Comment by exectails** [comment]
As this issue would basically never be fully completed until we implement every single item, I'll close this, but I'm going to add some examples for item script execution and the necessary buffs.
