### ISSUE TITLE
Add Base Job Skills

### ISSUE THREAD

**Issue by exectails** [NoCode-NoLife/melia#221]
To begin the journey towards full skill support, we'll implement the skills of the five base jobs, which will improve playability and help us solidify patterns for writing skill handlers. They will serve as the testing ground from where we can branch off to streamline the handling. This task is already under way.

**Swordsman**
- [x] Thrust
- [x] Bash
- [x] Gung Ho
- [x] Bear
- [x] Pain Barrier
- [x] Liberate

**Wizard**
- [x] Energy Bolt
- [x] Lethargy
- [x] Magic Shield
- [x] Earthquake
- [x] Magic Missile
- [x] Teleportation

**Archer**
- [x] Multi Shot
- [x] Oblique Shot
- [x] Swift Step
- [x] Twin Arrow
- [x] Concentration
- [x] Leap

**Cleric**
- [x] Heal
- [x] Cure
- [x] Smite
- [x] Fade
- [x] Guardian Saint

**Scout**
- [x] Cloaking
- [x] Dagger Slash
- [x] Oblique Fire
- [x] Double Attack
- [x] Free Step

**Comment by felipecastagnarodecarvalho** [comment]
#226 Oblique Fire and  Dagger Slash

**Comment by felipecastagnarodecarvalho** [comment]
#227 Oblique Fire and Twin Arrows

**Comment by felipecastagnarodecarvalho** [comment]
You made a Merge with a few Cleric Skills as well, right?

**Comment by exectails** [comment]
Yea, I forgot the check off Fade.

**Comment by exectails** [comment]
The base job skills have now all been implemented and execute their basic functionality.
