### ISSUE TITLE
Passive Skill Detection (for Quickbar)

### ISSUE THREAD

**Issue by Terotrous** [NoCode-NoLife/melia#281]
The current logic to determine if a skill is a passive doesn't work, and prevents many buffs from being added to the toolbar.  There is actually no way to detect if a skill is a passive with the fields we currently have.  We need the field TooltipType from skill.ies.

**Comment by exectails** [comment]
It seems weird to me that they would use a field called `Tooltip` for this purpose, but if it will give use better results, let's add it. We should keep an eye on it though, in case this isn't quite the right one either.
