### ISSUE TITLE
Normal Attacks don't apply attack types

### ISSUE THREAD

**Issue by Terotrous** [NoCode-NoLife/melia#284]
Currently, normal attacks don't apply attack types like strike and pierce because their attacktype in skills.txt is set to "None".  Should this be updated to have a damage type (ie, hammer_attack = AttackType.Strike?).  Do we need to get the attacktype in some other way for normal attacks?

**Comment by exectails** [comment]
I do think we need to use the item's attack type, which I added to our data earlier. In the chat there was also the open question of whether we would have to get the correct weapon, like for offhand attacks. But after a quick bit of research, it _seems_ like the weapon that determines the attack type is always the right hand one. I can't confirm this with 100% certainty, but it does appear to work like that. Unless we find evidence to the contrary, as well as a way of figuring out which weapon was actually used in the attack, I think that's how we should implement it for the time being.
