### ISSUE TITLE
Add internal server communication

### ISSUE THREAD

**Issue by exectails** [NoCode-NoLife/melia#3]
The channel servers have to communicate with the login server, so it can properly display their status in the barracks.

In Aura the internal connections use the same protocol as the clients and just socket connect to each other on start up, which is a little messy. Instead we should design a clean library for this, as it surely won't be the last time the servers have to communicate, and Aura will be able to benefit from it as well.

**Comment by sant0ro** [comment]
Using jSON for the Communication will be good. So you don't need doing directly not-secure socket connections, but Web Requests. Using RESTful API.

**Comment by exectails** [comment]
I've recently thought about that as well, it would certainly make things easier and cleaner. It wouldn't have much of an impact on performance, and CPs and other tools could easily communicate with the server.

**Comment by exectails** [comment]
@ovflowd This isn't reallly refactoring or maintenance, since there is no server communication at the moment. It's a new feature.

**Comment by ovflowd** [comment]
Oh! Gonna add the proper labels then! I guess I added those accidentally!

**Comment by exectails** [comment]
We now have basic communication between the clients, which allows us to send information such as server status updates, but there is room for improvement. We might want a dedicated server as the "coordinator" between the others, the communicator needs to be added to the web server, and we don't have a built-in way to make response requests yet, to query information from servers.

**Comment by exectails** [comment]
The web server is now connected as well and is able to officially request responses in a reliable way. As such, this issue will be considered complete.
