### ISSUE TITLE
Item Cooldowns

### ISSUE THREAD

**Issue by Terotrous** [NoCode-NoLife/melia#317]
Besides skills, items also have cooldowns that we need to implement.  It doesn't seem like the cooldowns are in the item-db, so we also probably have to find them.

**Comment by exectails** [comment]
This game uses a combined cooldown database, where cooldowns for various other systems come together. Are the cooldowns you're referring to in the cooldowns.txt?

**Comment by Terotrous** [comment]
It does seem like they are, though the OverheatResetTime doesn't seem correct (it's 6 seconds for almost everything in the file.  Skills clearly don't use this value since they use the time defined in skills.txt, but it's not correct for most of the items either).

**Comment by exectails** [comment]
Actually, skills do use the `OverheatResetTime`, but yea, I do see the cooldown in the item data. It is a little annoying that this data is so disjointed 🤔

**Comment by exectails** [comment]
Closing, since item cooldowns are now implemented.
