### ISSUE TITLE
Monster skill effects

### ISSUE THREAD

**Issue by Terotrous** [NoCode-NoLife/melia#319]
Some monster skills have added effects that we don't currently capture, such as the basic attack used by the Bat enemy, which is supposed to inflict UC_Bleed per the Bytool data.  Do we want to adjust simplemonsterattackskill to allow for a skill to inflict a status (possibly with a given percentage), or should we create custom handlers for these ones?

**Comment by exectails** [comment]
Our current monster skill setup is basically just there so our monsters _can_ attack, and it was never really meant to be expanded much. The idea was always that we would write dedicated skill handlers for anything that isn't straight forward. That being said, I suppose an attack + (de)buff falls somewhere in the middle, as it's still very simple.

Did you take a closer look at the skills in question by any chance? Do they all just call the target buff function?

**Comment by Terotrous** [comment]
I've looked at a few.  Some of them actually create Pads, which definitely can't be automated.  This particular one just inflicts a debuff.  Many others have no special effects at all (and thus match our existing implementation).

**Comment by exectails** [comment]
Right. I suspect there are more varied effects as well, just like with player skills, and those will likely require a bit more care. But those buff calls we can certainly add without overexerting us too much.

**Comment by exectails** [comment]
I looked into it a bit earlier today and now implemented calls for basic (de)buffs the skills appear to start, but I'll leave this issue open for the moment, in case there's more to it yet. For more involved effects, like the aforementioned pads, we should create dedicated handlers though.

**Comment by exectails** [comment]
As this issue was about the basic (de)buffs of monster skills that have now been added, and there hasn't been any reports about problems with this implementation, I'm going to consider this particular issue solved for the moment, though we naturally still have a lot of more complex monster skills to implement.
