### ISSUE TITLE
Nearby city data

### ISSUE THREAD

**Issue by exectails** [NoCode-NoLife/Melia#329]
We recently found a respawn option that gives players a way to restart at the nearest city. This option does not appear to universally be in use on officials, but it seems like a good option to have, since you could otherwise find yourself in a situation where you're semi-soft-locked in a region you can't escape on your own. We added a conf option to always enable this respawn option, but what we're currently lacking is reliable data on which city actually is the nearest city to a player's location.

The client has unfortunately not been very forthcoming with the necessary data, and so our map data currently uses Klaipeda as the closest nearby city for most maps. This isn't a pressing issue, but somewhere down the line we'd rather have more sensible data, where the nearest city actually is near a given map.

There are two options to accomplish this. We could either go through the map db, see where each map is located, and decide which city map is the closest, updating the db accordingly, or we could write a tool that takes our warp information and calculates the closest city based on warp jumps and distances between warps, with some sort of pathfinding algorithm.

A task we should tackle at some point, or perhaps a neat little project for someone who's looking for something to do.

The current map data can be found here: [system/db/maps.txt](https://github.com/NoCode-NoLife/melia/blob/master/system/db/maps.txt)

**Comment by kenedos** [comment]
Hello exec, the given script will parse all Melia warp .cs files in given `input/server/warps` folder recursively and find the path to the closest city. I've executed it on Melia master branch and also attached the text file output it generates.
[city_finder.zip](https://github.com/user-attachments/files/17270860/city_finder.zip)

**Comment by exectails** [comment]
Huh. Very nice. And quick, didn't we just talk about this yesterday? xD Nice job. This uses the number of jumps?

**Comment by kenedos** [comment]
Yes it's the number of "jumps" or warp portals you need to enter to get to a city. It is a "decent" unit of distance but may not be entirely correct visually. For example, a map may "look" to be closer to fedimian in the world map but take less warps to actuallly arrive to orsha, so there's that. But I think this solution should suffice for now.

**Comment by exectails** [comment]
I think we should probably not focus too much on the visual distance on the world map anyway, because as you alluded to, some warps don't make a whole lot of sense and you can end up on the other side of the game's world map. For officials this could perhaps make sense, because you might be more likely to be brought to the city that is closest to your progress in the story, but if you look a the world without that in mind, it seems to make more sense to go by how close you physically are to a city.
